import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'ru_RU': {
      'hello': 'Привет',
      'login': 'Войти',
      'logout': 'Выйти',
      'next': 'Дальше',
      'dismiss': 'Отмена',
      'new_ann': 'Новые заказы',
      'active_ann': 'Активные заказы',
      'first_name': "Ваше имя",
      'last_name': "Ваша фамилия",
      'middle_name': "Отчество",
      'phone_number': "Ваш номер телефона",
      'email': "Ваша почта",
      'birthday': "Дата рождения",
      'experience': "Ваш опыт",
      'degree': "Ваша степень",
      'profession': "Ваша специальность",
      'about_uz': "О себе на узбекском языке",
      'about_ru': "О себе на русском языке",
      'social_networks': "Социальные сети",
      'identification_info': 'Сделайте селфи и пройдите идентификацию',
    },
    'uz_UZ': {
      'hello': 'Salom',
      'login': 'Kirish',
      'logout': 'Chiqish',
      'next': 'Davom etish',
      'dismiss': 'Bekor qilish',
      'new_ann': 'Yangi buyurtmalar',
      'active_ann': 'Aktiv buyurtmalar',
      'first_name': "Ismingiz",
      'last_name': "Familiyangiz",
      'middle_name': "Otangizning ismi",
      'phone_number': "Telefon raqamingiz",
      'email': "Emailingiz",
      'birthday': "Tug'ilgan kuningiz",
      'experience': "Tajribangiz",
      'degree': "Darajangiz",
      'profession': "Yo'nalishingiz",
      'about_uz': "O'zbek tilida o'zingiz haqingizda",
      'about_ru': "Rus tilida o'zingiz haqingizda",
      'social_networks': "Ijtimoiy tarmoqlar",
      'identification_info': 'Selfi oling va identifikatsiyadan o\'ting',
    },
  };
}
