import 'package:get/get_navigation/src/root/internacionalization.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'ru_RU': {
      'hello': 'Привет',
      'login': 'Войти',
      'logout': 'Выход из системы',
      'next': 'Дальше',
      'dismiss': 'Отмена',
      'new_ann': 'Новые заказы',
      'active_ann': 'Активные заказы',
      'first_name': "Имя",
      'last_name': "Фамилия",
      'personal_info': "Личная информация",
      'middle_name': "Отчество",
      'phone_number': "Номер телефона",
      'email': "Электронная почта",
      'birthday': "Дата рождения",
      'experience': "Опыт",
      'degree': "Степень",
      'profession': "Специальность",
      'about_uz': "О себе на узбекском языке",
      'about_ru': "О себе на русском языке",
      'social_networks': "Социальные сети",
      'select_profession': 'Выберите специальность',
      'select_degree': 'Выберите степень',
      'identification_info': 'Сделайте селфи и пройдите идентификацию',
      'identification': 'Идентификация',
      'register_success': 'Вы успешно зарегистрировались в системе.',

      // --- Validation texts ---
      'valid_first_name': 'Введите имя',
      'valid_last_name': 'Введите фамилию',
      'valid_middle_name': 'Введите отчество',
      'valid_phone_number': 'Введите номер телефона',
      'valid_email': 'Введите почту',
      'valid_birthday': 'Введите дату рождения',
      'valid_experience': 'Введите опыт',
      'valid_degree': 'Выберите степень',
      'valid_profession': 'Выберите специальность',
      'valid_about_uz': 'Введите информацию о себе на узбекском языке',
      'valid_about_ru': 'Введите информацию о себе на русском языке',
      'valid_social_networks': 'Введите информацию о социальных сетях',
      'valid_language': 'Выберите язык',
      'valid_pnfl': 'Введите JSHSHR',

      // --- Medical Degrees ---
      'bachelor': 'Бакалавр',
      'master': 'Магистр',
      'phd': 'Кандидат наук (PhD)',
      'docent': 'Доцент',
      'professor': 'Профессор',
      'resident': 'Ординатор',
      'intern': 'Интерн',
      'specialist': 'Специалист',
      'doctor_sciences': 'Доктор наук',

      // --- Medical Professions ---
      'general_practitioner': 'Терапевт',
      'dentist': 'Стоматолог',
      'surgeon': 'Хирург',
      'pediatrician': 'Педиатр',
      'cardiologist': 'Кардиолог',
      'neurologist': 'Невролог',
      'oncologist': 'Онколог',
      'orthopedist': 'Ортопед',
      'gynecologist': 'Гинеколог',
      'urologist': 'Уролог',
      'dermatologist': 'Дерматолог',
      'psychiatrist': 'Психиатр',
      'radiologist': 'Рентгенолог',
      'ophthalmologist': 'Офтальмолог',
      'anesthesiologist': 'Анестезиолог',
      'endocrinologist': 'Эндокринолог',
      'family_doctor': 'Семейный врач',

      // --- Patient Info ---
      'patient_information': 'Информация о пациенте',
      'analysis_data': 'Результаты анализа',
      'diagnosis': 'Диагноз',
      'card': 'Карта',

      // --- Profile ---
      'documents': 'Документы',
      'work_and_schedule': 'Место работы и график',
      'profile': 'Профиль',

      // --- Work and Schedule ---
      'add_work_place': 'Добавить место работы',
      'add_day': 'Добавить день',
      'add_schedule': 'Добавить рабочие часы',
      'select_weekday': 'Выберите день недели',
      'lunch_time': 'Время обеда',
      'opening_hours': 'Часы работы',
      'name_of_clinic': 'Название клиники',
      'address_of_clinic': 'Адрес клиники',
      'region': 'Регион',
      'place': 'Место работы',
      'schedule': 'График работы',
    },
    'uz_UZ': {
      'hello': 'Salom',
      'login': 'Kirish',
      'logout': 'Tizimdan chiqildi',
      'next': 'Davom etish',
      'dismiss': 'Bekor qilish',
      'new_ann': 'Yangi buyurtmalar',
      'active_ann': 'Aktiv buyurtmalar',
      'first_name': "Ism",
      'last_name': "Familiya",
      'personal_info': "Shaxsiy ma'lumotlar",
      'middle_name': "Otasining ismi",
      'phone_number': "Telefon raqam",
      'email': "Email",
      'birthday': "Tug'ilgan kun",
      'experience': "Tajribangiz",
      'degree': "Darajangiz",
      'profession': "Yo'nalishingiz",
      'about_uz': "O'zbek tilida o'zingiz haqingizda",
      'about_ru': "Rus tilida o'zingiz haqingizda",
      'social_networks': "Ijtimoiy tarmoqlar",
      'select_profession': 'Iltimos yo\'nalishingizni tanlang',
      'select_degree': 'Iltimos darajangizni tanlang',
      'identification_info': 'Selfi oling va identifikatsiyadan o\'ting',
      'identification': 'Identifikatsiya',
      'register_success': 'Siz tizimdan muvaffaqiyatli ro\'yxatdan o\'tdingiz.',

      // --- Validation texts ---
      'valid_first_name': 'Iltimos ismingizni kiriting',
      'valid_last_name': 'Iltimos familiyangizni kiriting',
      'valid_middle_name': 'Iltimos otangizning ismini kiriting',
      'valid_phone_number': 'Iltimos telefon raqamingizni kiriting',
      'valid_email': 'Iltimos emailingizni kiriting',
      'valid_birthday': 'Iltimos tug\'ilgan kuningizni kiriting',
      'valid_experience': 'Iltimos tajribangizni kiriting',
      'valid_degree': 'Iltimos darajangizni tanlang',
      'valid_profession': 'Iltimos yo\'nalishingizni tanlang',
      'valid_about_uz':
          'Iltimos o\'zbek tilida o\'zingiz haqingizda ma\'lumot kiriting',
      'valid_about_ru':
          'Iltimos rus tilida o\'zingiz haqingizda ma\'lumot kiriting',
      'valid_social_networks':
          'Iltimos ijtimoiy tarmoqlar haqingizda ma\'lumot kiriting',
      'valid_language': 'Iltimos tilni tanlang',
      'valid_pnfl': 'Iltimos JSHSHR ni kiriting!',

      // --- Medical Degrees ---
      'bachelor': 'Bakalavr',
      'master': 'Magistr',
      'phd': 'PhD (Falsafa doktori)',
      'docent': 'Dotsent',
      'professor': 'Professor',
      'resident': 'Rezident',
      'intern': 'Intern',
      'specialist': 'Mutaxassis',
      'doctor_sciences': 'Fan doktori',

      // --- Medical Professions ---
      'general_practitioner': 'Terapevt',
      'dentist': 'Stomatolog',
      'surgeon': 'Jarroh',
      'pediatrician': 'Pediatr',
      'cardiologist': 'Kardiolog',
      'neurologist': 'Nevrolog',
      'oncologist': 'Onkolog',
      'orthopedist': 'Ortoped',
      'gynecologist': 'Ginekolog',
      'urologist': 'Urolog',
      'dermatologist': 'Dermatolog',
      'psychiatrist': 'Psixiatr',
      'radiologist': 'Rentgenolog',
      'ophthalmologist': 'Oftalmolog',
      'anesthesiologist': 'Anesteziolog',
      'endocrinologist': 'Endokrinolog',
      'family_doctor': 'Oilaviy shifokor',

      // --- Patient Info ---
      'patient_information': 'Bemor ma\'lumotlari',
      'analysis_data': 'Analiz natijasi',
      'diagnosis': 'Diagnos',
      'card': 'Karta',

      // --- Profile ---
      'documents': 'Hujjatlar',
      'work_and_schedule': 'Ish joyi va jadvallari',
      'profile': 'Profil',

      // --- Work and Schedule ---
      'add_work_place': 'Ish joyini qo\'shing',
      'add_day': 'Kun qo\'shish',
      'add_schedule': "Ish vaqtlarini qo'shish",
      'select_weekday': "Hafta kunini tanlang",
      'lunch_time': "Tushlik vaqti",
      'opening_hours': "Ish vaqti",
      'name_of_clinic': "Shifoxona nomi",
      'address_of_clinic': "Shifoxona manzili",
      'region': "Viloyat",
      'place': "Ish joyi",
      'schedule': "Ish jadvali",
    },
  };
}
